<?php

namespace JDJ\JediZoneBundle\Repository;
use JDJ\CoreBundle\Entity\EntityRepository;
use JDJ\JediZoneBundle\Entity\Activity;


/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

    /**
     * This function persist the activity
     *
     * @param Activity $activity
     */
    public function saveActivity(Activity $activity)
    {
        //persist the activity
        $this->_em->persist($activity);
        $this->_em->flush();
    }
}
