<?php

namespace JDJ\JediZoneBundle\Repository;
use JDJ\CoreBundle\Entity\EntityRepository;
use JDJ\JediZoneBundle\Entity\Notification;


/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    /**
     * This function persist the notification
     *
     * @param Notification $notification
     */
    public function saveNotification(Notification $notification)
    {
        //persist the notification
        $this->_em->persist($notification);
        $this->_em->flush();
    }
}
