<?php

namespace JDJ\JediZoneBundle\Repository;
use JDJ\CoreBundle\Entity\EntityRepository;


/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
}
