<?php
namespace JDJ\CollectionBundle\Repository;
use JDJ\CoreBundle\Entity\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
}