<?php

namespace JDJ\CollectionBundle\Repository;
use JDJ\CoreBundle\Entity\EntityRepository;

/**
 * ListElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListElementRepository extends EntityRepository
{
}
