<?php

namespace JDJ\CollectionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * listElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listElementRepository extends EntityRepository
{
}
