<?php
namespace JDJ\CollectionBundle\Repository;
use Doctrine\Common\Util\Debug;
use Doctrine\ORM\EntityRepository;
use JDJ\JeuBundle\Entity\Jeu;
use JDJ\UserBundle\Entity\User;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameAttributeRepository extends EntityRepository
{

    /**
     * This function returns the UserGameAttribute
     *
     * @param Jeu $game
     * @param User $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findUserGameAttribute(Jeu $game, User $user)
    {
        $queryBuilder = $this->createQueryBuilder('u')
            ->andWhere('u.jeu = :game')
            ->andWhere('u.user = :user')
            ->setParameter('game', $game)
            ->setParameter('user', $user);

        return $queryBuilder->getQuery()->getResult();

    }

}