<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160912184816 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, is_master TINYINT(1) NOT NULL, presentation VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, available_on DATETIME DEFAULT NULL, available_until DATETIME DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, releasedAt DATE DEFAULT NULL, UNIQUE INDEX UNIQ_A29B52377153098 (code), INDEX IDX_A29B5234584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_designer_product_variant (productvariant_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_B5D320D01855BE3F (productvariant_id), INDEX IDX_B5D320D0217BBB47 (person_id), PRIMARY KEY(productvariant_id, person_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_artist_product_variant (productvariant_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_DD0291E91855BE3F (productvariant_id), INDEX IDX_DD0291E9217BBB47 (person_id), PRIMARY KEY(productvariant_id, person_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_publisher_product_variant (productvariant_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_F4ABCB1B1855BE3F (productvariant_id), INDEX IDX_F4ABCB1B217BBB47 (person_id), PRIMARY KEY(productvariant_id, person_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant_option_value (variant_id INT NOT NULL, option_value_id INT NOT NULL, INDEX IDX_76CDAFA13B69A9AF (variant_id), INDEX IDX_76CDAFA1D957CA06 (option_value_id), PRIMARY KEY(variant_id, option_value_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_country (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_customer (id INT AUTO_INCREMENT NOT NULL, avatar_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, birthday DATETIME DEFAULT NULL, gender VARCHAR(1) DEFAULT \'u\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_7E82D5E6E7927C74 (email), UNIQUE INDEX UNIQ_7E82D5E6A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_7E82D5E677153098 (code), INDEX IDX_7E82D5E686383B10 (avatar_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_customer_group (customer_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_7FCF9B059395C3F3 (customer_id), INDEX IDX_7FCF9B05FE54D947 (group_id), PRIMARY KEY(customer_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_customer_list_element (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, object_id VARCHAR(64) NOT NULL, object_class VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, customerList_id INT NOT NULL, INDEX IDX_685D85D7BAE514C5 (customerList_id), INDEX IDX_685D85D74584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_post (id INT AUTO_INCREMENT NOT NULL, topic_id INT DEFAULT NULL, body LONGTEXT NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, replyTo_id INT DEFAULT NULL, createdBy_id INT DEFAULT NULL, updatedBy_id INT DEFAULT NULL, deletedBy_id INT DEFAULT NULL, INDEX IDX_3312CC5B1F55203D (topic_id), INDEX IDX_3312CC5BFC7F804C (replyTo_id), INDEX IDX_3312CC5B3174800F (createdBy_id), INDEX IDX_3312CC5B65FF1AEC (updatedBy_id), INDEX IDX_3312CC5B63D8C20E (deletedBy_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Taxon (id INT AUTO_INCREMENT NOT NULL, tree_root INT DEFAULT NULL, parent_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, tree_left INT NOT NULL, tree_right INT NOT NULL, tree_level INT NOT NULL, topicCount INT NOT NULL, UNIQUE INDEX UNIQ_9AA60CAF77153098 (code), INDEX IDX_9AA60CAFA977936C (tree_root), INDEX IDX_9AA60CAF727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_article (id INT AUTO_INCREMENT NOT NULL, topic_id INT DEFAULT NULL, product_id INT DEFAULT NULL, author_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, documentId VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, publishStartDate DATETIME DEFAULT NULL, publishEndDate DATETIME DEFAULT NULL, publishable TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, viewCount INT NOT NULL, averageRating DOUBLE PRECISION NOT NULL, materialRating DOUBLE PRECISION NOT NULL, rulesRating DOUBLE PRECISION NOT NULL, lifetimeRating DOUBLE PRECISION NOT NULL, mainTaxon_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_DBEDE01277153098 (code), UNIQUE INDEX UNIQ_DBEDE0125EB52FD5 (documentId), UNIQUE INDEX UNIQ_DBEDE0121F55203D (topic_id), INDEX IDX_DBEDE012A766DEB2 (mainTaxon_id), INDEX IDX_DBEDE0124584665A (product_id), INDEX IDX_DBEDE012F675F31B (author_id), INDEX publish_start_date_idx (publishStartDate), INDEX publishable_idx (publishable), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_dealer_price (id INT AUTO_INCREMENT NOT NULL, dealer_id INT DEFAULT NULL, product_id INT DEFAULT NULL, url VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, price INT NOT NULL, status VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5709B40F47645AE (url), INDEX IDX_5709B40249E6EA1 (dealer_id), INDEX IDX_5709B404584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, meta_keywords VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, shortDescription LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_105A908989D9B62 (slug), INDEX IDX_105A9082C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_customer_list (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, code VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_2ED5E5999395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_review (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, rating INT NOT NULL, comment LONGTEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_C7056A994584665A (product_id), INDEX IDX_C7056A99F675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_customer_avatar (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_game_play (id INT AUTO_INCREMENT NOT NULL, topic_id INT DEFAULT NULL, product_id INT NOT NULL, author_id INT NOT NULL, code VARCHAR(255) DEFAULT NULL, duration DATETIME DEFAULT NULL, playerCount INT DEFAULT NULL, playedAt DATE DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B97D18CC77153098 (code), UNIQUE INDEX UNIQ_B97D18CC1F55203D (topic_id), INDEX IDX_B97D18CC4584665A (product_id), INDEX IDX_B97D18CCF675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_person_image (id INT AUTO_INCREMENT NOT NULL, person_id INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, is_main TINYINT(1) NOT NULL, INDEX IDX_8BC5367C217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Notification (id INT AUTO_INCREMENT NOT NULL, topic_id INT DEFAULT NULL, recipient_id INT NOT NULL, is_read TINYINT(1) NOT NULL, message LONGTEXT NOT NULL, target VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_A765AD321F55203D (topic_id), INDEX IDX_A765AD32E92F8F78 (recipient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_topic (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, postCount INT NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, mainPost_id INT DEFAULT NULL, createdBy_id INT DEFAULT NULL, updatedBy_id INT DEFAULT NULL, deletedBy_id INT DEFAULT NULL, mainTaxon_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_F299315AE21B6525 (mainPost_id), INDEX IDX_F299315A3174800F (createdBy_id), INDEX IDX_F299315A65FF1AEC (updatedBy_id), INDEX IDX_F299315A63D8C20E (deletedBy_id), INDEX IDX_F299315AA766DEB2 (mainTaxon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_topic_follower (topic_id INT NOT NULL, customerinterface_id INT NOT NULL, INDEX IDX_1B075FD01F55203D (topic_id), INDEX IDX_1B075FD0F6FD7074 (customerinterface_id), PRIMARY KEY(topic_id, customerinterface_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_prices_list (id INT AUTO_INCREMENT NOT NULL, dealer_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, headers TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_341DB6E7249E6EA1 (dealer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_game_play_image (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, gamePlay_id INT DEFAULT NULL, INDEX IDX_2A6557916EEC1E6A (gamePlay_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_dealer_image (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_variant_image (id INT AUTO_INCREMENT NOT NULL, variant_id INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, is_main TINYINT(1) NOT NULL, is_material TINYINT(1) NOT NULL, INDEX IDX_C6B77D5D3B69A9AF (variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_dealer (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_161791EB77153098 (code), UNIQUE INDEX UNIQ_161791EB3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_article_review (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, rating INT NOT NULL, comment LONGTEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, reviewSubject_id INT DEFAULT NULL, INDEX IDX_4764CDD6970EE54B (reviewSubject_id), INDEX IDX_4764CDD6F675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_taxon_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, permalink VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_1487DFCF2C2AC5D3 (translatable_id), UNIQUE INDEX permalink_uidx (locale, permalink), UNIQUE INDEX sylius_taxon_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_player (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, score DOUBLE PRECISION DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, gamePlay_id INT NOT NULL, INDEX IDX_99ADD28C6EEC1E6A (gamePlay_id), INDEX IDX_99ADD28C9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_person (id INT AUTO_INCREMENT NOT NULL, lastName VARCHAR(50) NOT NULL, firstName VARCHAR(50) NOT NULL, website VARCHAR(200) DEFAULT NULL, description LONGTEXT DEFAULT NULL, slug VARCHAR(128) NOT NULL, UNIQUE INDEX UNIQ_3568799F989D9B62 (slug), INDEX search_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jdj_person_taxon (person_id INT NOT NULL, taxoninterface_id INT NOT NULL, INDEX IDX_159F1188217BBB47 (person_id), INDEX IDX_159F11887E2DD0E0 (taxoninterface_id), PRIMARY KEY(person_id, taxoninterface_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product (id INT AUTO_INCREMENT NOT NULL, archetype_id INT DEFAULT NULL, available_on DATETIME DEFAULT NULL, available_until DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, enabled TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, ageMin INT UNSIGNED DEFAULT NULL, joueurMin INT UNSIGNED DEFAULT NULL, joueurMax INT UNSIGNED DEFAULT NULL, durationMin INT UNSIGNED DEFAULT NULL, durationMax INT UNSIGNED DEFAULT NULL, durationByPlayer TINYINT(1) NOT NULL, materiel LONGTEXT DEFAULT NULL, but LONGTEXT DEFAULT NULL, averageRating DOUBLE PRECISION NOT NULL, mainTaxon_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_677B9B7477153098 (code), INDEX IDX_677B9B74732C6CC7 (archetype_id), INDEX IDX_677B9B74A766DEB2 (mainTaxon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_taxon (product_id INT NOT NULL, taxoninterface_id INT NOT NULL, INDEX IDX_169C6CD94584665A (product_id), INDEX IDX_169C6CD97E2DD0E0 (taxoninterface_id), PRIMARY KEY(product_id, taxoninterface_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_options (product_id INT NOT NULL, option_id INT NOT NULL, INDEX IDX_2B5FF0094584665A (product_id), INDEX IDX_2B5FF009A7C41D6F (option_id), PRIMARY KEY(product_id, option_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_archetype (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D19FF85177153098 (code), INDEX IDX_D19FF851727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_archetype_option (product_archetype_id INT NOT NULL, option_id INT NOT NULL, INDEX IDX_BCE763A7FE884EAC (product_archetype_id), INDEX IDX_BCE763A7A7C41D6F (option_id), PRIMARY KEY(product_archetype_id, option_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_archetype_attribute (archetype_id INT NOT NULL, attribute_id INT NOT NULL, INDEX IDX_97763342732C6CC7 (archetype_id), INDEX IDX_97763342B6E62EFA (attribute_id), PRIMARY KEY(archetype_id, attribute_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_value (id INT AUTO_INCREMENT NOT NULL, option_id INT NOT NULL, code VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_F7FF7D4B77153098 (code), INDEX IDX_F7FF7D4BA7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_E4C0EBEF77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_93850EBA2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_attribute_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_value_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, presentation VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_8D4382DC2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_option_value_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute_value (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, attribute_id INT NOT NULL, text_value LONGTEXT DEFAULT NULL, boolean_value TINYINT(1) DEFAULT NULL, integer_value INT DEFAULT NULL, float_value DOUBLE PRECISION DEFAULT NULL, datetime_value DATETIME DEFAULT NULL, date_value DATE DEFAULT NULL, INDEX IDX_8A053E544584665A (product_id), INDEX IDX_8A053E54B6E62EFA (attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_attribute (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, storage_type VARCHAR(255) NOT NULL, configuration LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_BFAF484A77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_archetype_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_E0BA36D2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_archetype_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_option_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT NOT NULL, presentation VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_CBA491AD2C2AC5D3 (translatable_id), UNIQUE INDEX sylius_product_option_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, association_type_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_48E9CDAB4584665A (product_id), INDEX IDX_48E9CDABB1E1C39 (association_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_product_association_product (association_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_A427B983EFB9C8A5 (association_id), INDEX IDX_A427B9834584665A (product_id), PRIMARY KEY(association_id, product_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_association_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_6237029277153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_user_oauth (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, provider VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, access_token VARCHAR(255) DEFAULT NULL, INDEX IDX_C3471B78A76ED395 (user_id), UNIQUE INDEX user_provider (user_id, provider), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_user (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, username VARCHAR(255) DEFAULT NULL, username_canonical VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, credentials_expire_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_569A33C09395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sylius_email (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, template VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, subject VARCHAR(255) NOT NULL, sender_name VARCHAR(255) DEFAULT NULL, sender_address VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_732D4E1577153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_namespaces (prefix VARCHAR(255) NOT NULL, uri VARCHAR(255) NOT NULL, PRIMARY KEY(prefix)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_workspaces (name VARCHAR(255) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) NOT NULL, parent VARCHAR(255) NOT NULL, local_name VARCHAR(255) NOT NULL, namespace VARCHAR(255) NOT NULL, workspace_name VARCHAR(255) NOT NULL, identifier VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, props LONGTEXT NOT NULL, numerical_props LONGTEXT DEFAULT NULL, depth INT NOT NULL, sort_order INT DEFAULT NULL, UNIQUE INDEX UNIQ_A4624AD7B548B0F1AC10DC4 (path, workspace_name), UNIQUE INDEX UNIQ_A4624AD7772E836A1AC10DC4 (identifier, workspace_name), INDEX IDX_A4624AD73D8E604F (parent), INDEX IDX_A4624AD78CDE5729 (type), INDEX IDX_A4624AD7623C14D533E16B56 (local_name, namespace), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_internal_index_types (type VARCHAR(255) NOT NULL, node_id INT NOT NULL, PRIMARY KEY(type, node_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_binarydata (id INT AUTO_INCREMENT NOT NULL, node_id INT NOT NULL, property_name VARCHAR(255) NOT NULL, workspace_name VARCHAR(255) NOT NULL, idx INT DEFAULT 0 NOT NULL, data LONGBLOB NOT NULL, UNIQUE INDEX UNIQ_37E65615460D9FD7413BC13C1AC10DC4E7087E10 (node_id, property_name, workspace_name, idx), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes_references (source_id INT NOT NULL, source_property_name VARCHAR(220) NOT NULL, target_id INT NOT NULL, INDEX IDX_F3BF7E1158E0B66 (target_id), PRIMARY KEY(source_id, source_property_name, target_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_nodes_weakreferences (source_id INT NOT NULL, source_property_name VARCHAR(220) NOT NULL, target_id INT NOT NULL, INDEX IDX_F0E4F6FA158E0B66 (target_id), PRIMARY KEY(source_id, source_property_name, target_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_nodes (node_type_id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, supertypes VARCHAR(255) NOT NULL, is_abstract TINYINT(1) NOT NULL, is_mixin TINYINT(1) NOT NULL, queryable TINYINT(1) NOT NULL, orderable_child_nodes TINYINT(1) NOT NULL, primary_item VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_34B0A8095E237E06 (name), PRIMARY KEY(node_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_props (node_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, protected TINYINT(1) NOT NULL, auto_created TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, on_parent_version INT NOT NULL, multiple TINYINT(1) NOT NULL, fulltext_searchable TINYINT(1) NOT NULL, query_orderable TINYINT(1) NOT NULL, required_type INT NOT NULL, query_operators INT NOT NULL, default_value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(node_type_id, name)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phpcr_type_childs (node_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, protected TINYINT(1) NOT NULL, auto_created TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, on_parent_version INT NOT NULL, primary_types VARCHAR(255) NOT NULL, default_type VARCHAR(255) DEFAULT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE sylius_product_variant ADD CONSTRAINT FK_A29B5234584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_designer_product_variant ADD CONSTRAINT FK_B5D320D01855BE3F FOREIGN KEY (productvariant_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_designer_product_variant ADD CONSTRAINT FK_B5D320D0217BBB47 FOREIGN KEY (person_id) REFERENCES jdj_person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_artist_product_variant ADD CONSTRAINT FK_DD0291E91855BE3F FOREIGN KEY (productvariant_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_artist_product_variant ADD CONSTRAINT FK_DD0291E9217BBB47 FOREIGN KEY (person_id) REFERENCES jdj_person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_publisher_product_variant ADD CONSTRAINT FK_F4ABCB1B1855BE3F FOREIGN KEY (productvariant_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_publisher_product_variant ADD CONSTRAINT FK_F4ABCB1B217BBB47 FOREIGN KEY (person_id) REFERENCES jdj_person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA13B69A9AF FOREIGN KEY (variant_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA1D957CA06 FOREIGN KEY (option_value_id) REFERENCES sylius_product_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_customer ADD CONSTRAINT FK_7E82D5E686383B10 FOREIGN KEY (avatar_id) REFERENCES jdj_customer_avatar (id)');
        $this->addSql('ALTER TABLE sylius_customer_group ADD CONSTRAINT FK_7FCF9B059395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_customer_group ADD CONSTRAINT FK_7FCF9B05FE54D947 FOREIGN KEY (group_id) REFERENCES sylius_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_customer_list_element ADD CONSTRAINT FK_685D85D7BAE514C5 FOREIGN KEY (customerList_id) REFERENCES jdj_customer_list (id)');
        $this->addSql('ALTER TABLE jdj_customer_list_element ADD CONSTRAINT FK_685D85D74584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id)');
        $this->addSql('ALTER TABLE jdj_post ADD CONSTRAINT FK_3312CC5B1F55203D FOREIGN KEY (topic_id) REFERENCES jdj_topic (id)');
        $this->addSql('ALTER TABLE jdj_post ADD CONSTRAINT FK_3312CC5BFC7F804C FOREIGN KEY (replyTo_id) REFERENCES jdj_post (id)');
        $this->addSql('ALTER TABLE jdj_post ADD CONSTRAINT FK_3312CC5B3174800F FOREIGN KEY (createdBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_post ADD CONSTRAINT FK_3312CC5B65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_post ADD CONSTRAINT FK_3312CC5B63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE Taxon ADD CONSTRAINT FK_9AA60CAFA977936C FOREIGN KEY (tree_root) REFERENCES Taxon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Taxon ADD CONSTRAINT FK_9AA60CAF727ACA70 FOREIGN KEY (parent_id) REFERENCES Taxon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_article ADD CONSTRAINT FK_DBEDE0121F55203D FOREIGN KEY (topic_id) REFERENCES jdj_topic (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_article ADD CONSTRAINT FK_DBEDE012A766DEB2 FOREIGN KEY (mainTaxon_id) REFERENCES Taxon (id)');
        $this->addSql('ALTER TABLE jdj_article ADD CONSTRAINT FK_DBEDE0124584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id)');
        $this->addSql('ALTER TABLE jdj_article ADD CONSTRAINT FK_DBEDE012F675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE jdj_dealer_price ADD CONSTRAINT FK_5709B40249E6EA1 FOREIGN KEY (dealer_id) REFERENCES jdj_dealer (id)');
        $this->addSql('ALTER TABLE jdj_dealer_price ADD CONSTRAINT FK_5709B404584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id)');
        $this->addSql('ALTER TABLE sylius_product_translation ADD CONSTRAINT FK_105A9082C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_customer_list ADD CONSTRAINT FK_2ED5E5999395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE sylius_product_review ADD CONSTRAINT FK_C7056A994584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_review ADD CONSTRAINT FK_C7056A99F675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE jdj_game_play ADD CONSTRAINT FK_B97D18CC1F55203D FOREIGN KEY (topic_id) REFERENCES jdj_topic (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_game_play ADD CONSTRAINT FK_B97D18CC4584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id)');
        $this->addSql('ALTER TABLE jdj_game_play ADD CONSTRAINT FK_B97D18CCF675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE jdj_person_image ADD CONSTRAINT FK_8BC5367C217BBB47 FOREIGN KEY (person_id) REFERENCES jdj_person (id)');
        $this->addSql('ALTER TABLE Notification ADD CONSTRAINT FK_A765AD321F55203D FOREIGN KEY (topic_id) REFERENCES jdj_topic (id)');
        $this->addSql('ALTER TABLE Notification ADD CONSTRAINT FK_A765AD32E92F8F78 FOREIGN KEY (recipient_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE jdj_topic ADD CONSTRAINT FK_F299315AE21B6525 FOREIGN KEY (mainPost_id) REFERENCES jdj_post (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_topic ADD CONSTRAINT FK_F299315A3174800F FOREIGN KEY (createdBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_topic ADD CONSTRAINT FK_F299315A65FF1AEC FOREIGN KEY (updatedBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_topic ADD CONSTRAINT FK_F299315A63D8C20E FOREIGN KEY (deletedBy_id) REFERENCES sylius_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE jdj_topic ADD CONSTRAINT FK_F299315AA766DEB2 FOREIGN KEY (mainTaxon_id) REFERENCES Taxon (id)');
        $this->addSql('ALTER TABLE jdj_topic_follower ADD CONSTRAINT FK_1B075FD01F55203D FOREIGN KEY (topic_id) REFERENCES jdj_topic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_topic_follower ADD CONSTRAINT FK_1B075FD0F6FD7074 FOREIGN KEY (customerinterface_id) REFERENCES sylius_customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_prices_list ADD CONSTRAINT FK_341DB6E7249E6EA1 FOREIGN KEY (dealer_id) REFERENCES jdj_dealer (id)');
        $this->addSql('ALTER TABLE jdj_game_play_image ADD CONSTRAINT FK_2A6557916EEC1E6A FOREIGN KEY (gamePlay_id) REFERENCES jdj_game_play (id)');
        $this->addSql('ALTER TABLE sylius_product_variant_image ADD CONSTRAINT FK_C6B77D5D3B69A9AF FOREIGN KEY (variant_id) REFERENCES sylius_product_variant (id)');
        $this->addSql('ALTER TABLE jdj_dealer ADD CONSTRAINT FK_161791EB3DA5256D FOREIGN KEY (image_id) REFERENCES jdj_dealer_image (id)');
        $this->addSql('ALTER TABLE jdj_article_review ADD CONSTRAINT FK_4764CDD6970EE54B FOREIGN KEY (reviewSubject_id) REFERENCES jdj_article (id)');
        $this->addSql('ALTER TABLE jdj_article_review ADD CONSTRAINT FK_4764CDD6F675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE sylius_taxon_translation ADD CONSTRAINT FK_1487DFCF2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES Taxon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_player ADD CONSTRAINT FK_99ADD28C6EEC1E6A FOREIGN KEY (gamePlay_id) REFERENCES jdj_game_play (id)');
        $this->addSql('ALTER TABLE jdj_player ADD CONSTRAINT FK_99ADD28C9395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id)');
        $this->addSql('ALTER TABLE jdj_person_taxon ADD CONSTRAINT FK_159F1188217BBB47 FOREIGN KEY (person_id) REFERENCES jdj_person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE jdj_person_taxon ADD CONSTRAINT FK_159F11887E2DD0E0 FOREIGN KEY (taxoninterface_id) REFERENCES Taxon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product ADD CONSTRAINT FK_677B9B74732C6CC7 FOREIGN KEY (archetype_id) REFERENCES sylius_archetype (id)');
        $this->addSql('ALTER TABLE sylius_product ADD CONSTRAINT FK_677B9B74A766DEB2 FOREIGN KEY (mainTaxon_id) REFERENCES Taxon (id)');
        $this->addSql('ALTER TABLE sylius_product_taxon ADD CONSTRAINT FK_169C6CD94584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_taxon ADD CONSTRAINT FK_169C6CD97E2DD0E0 FOREIGN KEY (taxoninterface_id) REFERENCES Taxon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF0094584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF009A7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_archetype ADD CONSTRAINT FK_D19FF851727ACA70 FOREIGN KEY (parent_id) REFERENCES sylius_archetype (id)');
        $this->addSql('ALTER TABLE sylius_product_archetype_option ADD CONSTRAINT FK_BCE763A7FE884EAC FOREIGN KEY (product_archetype_id) REFERENCES sylius_archetype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_archetype_option ADD CONSTRAINT FK_BCE763A7A7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_archetype_attribute ADD CONSTRAINT FK_97763342732C6CC7 FOREIGN KEY (archetype_id) REFERENCES sylius_archetype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_archetype_attribute ADD CONSTRAINT FK_97763342B6E62EFA FOREIGN KEY (attribute_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_option_value ADD CONSTRAINT FK_F7FF7D4BA7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation ADD CONSTRAINT FK_93850EBA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation ADD CONSTRAINT FK_8D4382DC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E544584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E54B6E62EFA FOREIGN KEY (attribute_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_archetype_translation ADD CONSTRAINT FK_E0BA36D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_archetype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_option_translation ADD CONSTRAINT FK_CBA491AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDAB4584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDABB1E1C39 FOREIGN KEY (association_type_id) REFERENCES sylius_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B983EFB9C8A5 FOREIGN KEY (association_id) REFERENCES sylius_product_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B9834584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sylius_user_oauth ADD CONSTRAINT FK_C3471B78A76ED395 FOREIGN KEY (user_id) REFERENCES sylius_user (id)');
        $this->addSql('ALTER TABLE sylius_user ADD CONSTRAINT FK_569A33C09395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE jdj_designer_product_variant DROP FOREIGN KEY FK_B5D320D01855BE3F');
        $this->addSql('ALTER TABLE jdj_artist_product_variant DROP FOREIGN KEY FK_DD0291E91855BE3F');
        $this->addSql('ALTER TABLE jdj_publisher_product_variant DROP FOREIGN KEY FK_F4ABCB1B1855BE3F');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP FOREIGN KEY FK_76CDAFA13B69A9AF');
        $this->addSql('ALTER TABLE sylius_product_variant_image DROP FOREIGN KEY FK_C6B77D5D3B69A9AF');
        $this->addSql('ALTER TABLE sylius_customer_group DROP FOREIGN KEY FK_7FCF9B059395C3F3');
        $this->addSql('ALTER TABLE jdj_article DROP FOREIGN KEY FK_DBEDE012F675F31B');
        $this->addSql('ALTER TABLE jdj_customer_list DROP FOREIGN KEY FK_2ED5E5999395C3F3');
        $this->addSql('ALTER TABLE sylius_product_review DROP FOREIGN KEY FK_C7056A99F675F31B');
        $this->addSql('ALTER TABLE jdj_game_play DROP FOREIGN KEY FK_B97D18CCF675F31B');
        $this->addSql('ALTER TABLE Notification DROP FOREIGN KEY FK_A765AD32E92F8F78');
        $this->addSql('ALTER TABLE jdj_topic_follower DROP FOREIGN KEY FK_1B075FD0F6FD7074');
        $this->addSql('ALTER TABLE jdj_article_review DROP FOREIGN KEY FK_4764CDD6F675F31B');
        $this->addSql('ALTER TABLE jdj_player DROP FOREIGN KEY FK_99ADD28C9395C3F3');
        $this->addSql('ALTER TABLE sylius_user DROP FOREIGN KEY FK_569A33C09395C3F3');
        $this->addSql('ALTER TABLE jdj_post DROP FOREIGN KEY FK_3312CC5BFC7F804C');
        $this->addSql('ALTER TABLE jdj_topic DROP FOREIGN KEY FK_F299315AE21B6525');
        $this->addSql('ALTER TABLE Taxon DROP FOREIGN KEY FK_9AA60CAFA977936C');
        $this->addSql('ALTER TABLE Taxon DROP FOREIGN KEY FK_9AA60CAF727ACA70');
        $this->addSql('ALTER TABLE jdj_article DROP FOREIGN KEY FK_DBEDE012A766DEB2');
        $this->addSql('ALTER TABLE jdj_topic DROP FOREIGN KEY FK_F299315AA766DEB2');
        $this->addSql('ALTER TABLE sylius_taxon_translation DROP FOREIGN KEY FK_1487DFCF2C2AC5D3');
        $this->addSql('ALTER TABLE jdj_person_taxon DROP FOREIGN KEY FK_159F11887E2DD0E0');
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B74A766DEB2');
        $this->addSql('ALTER TABLE sylius_product_taxon DROP FOREIGN KEY FK_169C6CD97E2DD0E0');
        $this->addSql('ALTER TABLE jdj_article_review DROP FOREIGN KEY FK_4764CDD6970EE54B');
        $this->addSql('ALTER TABLE jdj_customer_list_element DROP FOREIGN KEY FK_685D85D7BAE514C5');
        $this->addSql('ALTER TABLE sylius_customer DROP FOREIGN KEY FK_7E82D5E686383B10');
        $this->addSql('ALTER TABLE jdj_game_play_image DROP FOREIGN KEY FK_2A6557916EEC1E6A');
        $this->addSql('ALTER TABLE jdj_player DROP FOREIGN KEY FK_99ADD28C6EEC1E6A');
        $this->addSql('ALTER TABLE jdj_post DROP FOREIGN KEY FK_3312CC5B1F55203D');
        $this->addSql('ALTER TABLE jdj_article DROP FOREIGN KEY FK_DBEDE0121F55203D');
        $this->addSql('ALTER TABLE jdj_game_play DROP FOREIGN KEY FK_B97D18CC1F55203D');
        $this->addSql('ALTER TABLE Notification DROP FOREIGN KEY FK_A765AD321F55203D');
        $this->addSql('ALTER TABLE jdj_topic_follower DROP FOREIGN KEY FK_1B075FD01F55203D');
        $this->addSql('ALTER TABLE jdj_dealer DROP FOREIGN KEY FK_161791EB3DA5256D');
        $this->addSql('ALTER TABLE jdj_dealer_price DROP FOREIGN KEY FK_5709B40249E6EA1');
        $this->addSql('ALTER TABLE jdj_prices_list DROP FOREIGN KEY FK_341DB6E7249E6EA1');
        $this->addSql('ALTER TABLE jdj_designer_product_variant DROP FOREIGN KEY FK_B5D320D0217BBB47');
        $this->addSql('ALTER TABLE jdj_artist_product_variant DROP FOREIGN KEY FK_DD0291E9217BBB47');
        $this->addSql('ALTER TABLE jdj_publisher_product_variant DROP FOREIGN KEY FK_F4ABCB1B217BBB47');
        $this->addSql('ALTER TABLE jdj_person_image DROP FOREIGN KEY FK_8BC5367C217BBB47');
        $this->addSql('ALTER TABLE jdj_person_taxon DROP FOREIGN KEY FK_159F1188217BBB47');
        $this->addSql('ALTER TABLE sylius_product_variant DROP FOREIGN KEY FK_A29B5234584665A');
        $this->addSql('ALTER TABLE jdj_customer_list_element DROP FOREIGN KEY FK_685D85D74584665A');
        $this->addSql('ALTER TABLE jdj_article DROP FOREIGN KEY FK_DBEDE0124584665A');
        $this->addSql('ALTER TABLE jdj_dealer_price DROP FOREIGN KEY FK_5709B404584665A');
        $this->addSql('ALTER TABLE sylius_product_translation DROP FOREIGN KEY FK_105A9082C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_review DROP FOREIGN KEY FK_C7056A994584665A');
        $this->addSql('ALTER TABLE jdj_game_play DROP FOREIGN KEY FK_B97D18CC4584665A');
        $this->addSql('ALTER TABLE sylius_product_taxon DROP FOREIGN KEY FK_169C6CD94584665A');
        $this->addSql('ALTER TABLE sylius_product_options DROP FOREIGN KEY FK_2B5FF0094584665A');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP FOREIGN KEY FK_8A053E544584665A');
        $this->addSql('ALTER TABLE sylius_product_association DROP FOREIGN KEY FK_48E9CDAB4584665A');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP FOREIGN KEY FK_A427B9834584665A');
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B74732C6CC7');
        $this->addSql('ALTER TABLE sylius_archetype DROP FOREIGN KEY FK_D19FF851727ACA70');
        $this->addSql('ALTER TABLE sylius_product_archetype_option DROP FOREIGN KEY FK_BCE763A7FE884EAC');
        $this->addSql('ALTER TABLE sylius_product_archetype_attribute DROP FOREIGN KEY FK_97763342732C6CC7');
        $this->addSql('ALTER TABLE sylius_product_archetype_translation DROP FOREIGN KEY FK_E0BA36D2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP FOREIGN KEY FK_76CDAFA1D957CA06');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation DROP FOREIGN KEY FK_8D4382DC2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_options DROP FOREIGN KEY FK_2B5FF009A7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_archetype_option DROP FOREIGN KEY FK_BCE763A7A7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_option_value DROP FOREIGN KEY FK_F7FF7D4BA7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_option_translation DROP FOREIGN KEY FK_CBA491AD2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_archetype_attribute DROP FOREIGN KEY FK_97763342B6E62EFA');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation DROP FOREIGN KEY FK_93850EBA2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP FOREIGN KEY FK_8A053E54B6E62EFA');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP FOREIGN KEY FK_A427B983EFB9C8A5');
        $this->addSql('ALTER TABLE sylius_product_association DROP FOREIGN KEY FK_48E9CDABB1E1C39');
        $this->addSql('ALTER TABLE sylius_customer_group DROP FOREIGN KEY FK_7FCF9B05FE54D947');
        $this->addSql('ALTER TABLE jdj_post DROP FOREIGN KEY FK_3312CC5B3174800F');
        $this->addSql('ALTER TABLE jdj_post DROP FOREIGN KEY FK_3312CC5B65FF1AEC');
        $this->addSql('ALTER TABLE jdj_post DROP FOREIGN KEY FK_3312CC5B63D8C20E');
        $this->addSql('ALTER TABLE jdj_topic DROP FOREIGN KEY FK_F299315A3174800F');
        $this->addSql('ALTER TABLE jdj_topic DROP FOREIGN KEY FK_F299315A65FF1AEC');
        $this->addSql('ALTER TABLE jdj_topic DROP FOREIGN KEY FK_F299315A63D8C20E');
        $this->addSql('ALTER TABLE sylius_user_oauth DROP FOREIGN KEY FK_C3471B78A76ED395');
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE sylius_product_variant');
        $this->addSql('DROP TABLE jdj_designer_product_variant');
        $this->addSql('DROP TABLE jdj_artist_product_variant');
        $this->addSql('DROP TABLE jdj_publisher_product_variant');
        $this->addSql('DROP TABLE sylius_product_variant_option_value');
        $this->addSql('DROP TABLE jdj_country');
        $this->addSql('DROP TABLE sylius_customer');
        $this->addSql('DROP TABLE sylius_customer_group');
        $this->addSql('DROP TABLE jdj_customer_list_element');
        $this->addSql('DROP TABLE jdj_post');
        $this->addSql('DROP TABLE Taxon');
        $this->addSql('DROP TABLE jdj_article');
        $this->addSql('DROP TABLE jdj_dealer_price');
        $this->addSql('DROP TABLE sylius_product_translation');
        $this->addSql('DROP TABLE jdj_customer_list');
        $this->addSql('DROP TABLE sylius_product_review');
        $this->addSql('DROP TABLE jdj_customer_avatar');
        $this->addSql('DROP TABLE jdj_game_play');
        $this->addSql('DROP TABLE jdj_person_image');
        $this->addSql('DROP TABLE Notification');
        $this->addSql('DROP TABLE jdj_topic');
        $this->addSql('DROP TABLE jdj_topic_follower');
        $this->addSql('DROP TABLE jdj_prices_list');
        $this->addSql('DROP TABLE jdj_game_play_image');
        $this->addSql('DROP TABLE jdj_dealer_image');
        $this->addSql('DROP TABLE sylius_product_variant_image');
        $this->addSql('DROP TABLE jdj_dealer');
        $this->addSql('DROP TABLE jdj_article_review');
        $this->addSql('DROP TABLE sylius_taxon_translation');
        $this->addSql('DROP TABLE jdj_player');
        $this->addSql('DROP TABLE jdj_person');
        $this->addSql('DROP TABLE jdj_person_taxon');
        $this->addSql('DROP TABLE sylius_product');
        $this->addSql('DROP TABLE sylius_product_taxon');
        $this->addSql('DROP TABLE sylius_product_options');
        $this->addSql('DROP TABLE sylius_archetype');
        $this->addSql('DROP TABLE sylius_product_archetype_option');
        $this->addSql('DROP TABLE sylius_product_archetype_attribute');
        $this->addSql('DROP TABLE sylius_product_option_value');
        $this->addSql('DROP TABLE sylius_product_option');
        $this->addSql('DROP TABLE sylius_product_attribute_translation');
        $this->addSql('DROP TABLE sylius_product_option_value_translation');
        $this->addSql('DROP TABLE sylius_product_attribute_value');
        $this->addSql('DROP TABLE sylius_product_attribute');
        $this->addSql('DROP TABLE sylius_product_archetype_translation');
        $this->addSql('DROP TABLE sylius_product_option_translation');
        $this->addSql('DROP TABLE sylius_product_association');
        $this->addSql('DROP TABLE sylius_product_association_product');
        $this->addSql('DROP TABLE sylius_association_type');
        $this->addSql('DROP TABLE sylius_user_oauth');
        $this->addSql('DROP TABLE sylius_group');
        $this->addSql('DROP TABLE sylius_user');
        $this->addSql('DROP TABLE sylius_email');
        $this->addSql('DROP TABLE phpcr_namespaces');
        $this->addSql('DROP TABLE phpcr_workspaces');
        $this->addSql('DROP TABLE phpcr_nodes');
        $this->addSql('DROP TABLE phpcr_internal_index_types');
        $this->addSql('DROP TABLE phpcr_binarydata');
        $this->addSql('DROP TABLE phpcr_nodes_references');
        $this->addSql('DROP TABLE phpcr_nodes_weakreferences');
        $this->addSql('DROP TABLE phpcr_type_nodes');
        $this->addSql('DROP TABLE phpcr_type_props');
        $this->addSql('DROP TABLE phpcr_type_childs');
    }
}
