#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

run_behat() {
    local code=0

    run_command "cp travis/suites/application/assets/old-behat.yml behat.yml" || code=$?
    run_command "sed -i 's/en_US/fr_FR/' app/config/config_test.yml" || code=$?

    print_header "Testing (Behat - brand new, regular scenarios; ~@javascript && ~@todo && ~@cli)" "Jedisjeux"
    run_command "bin/behat --strict --no-interaction -vvv -f progress --tags=\"~@javascript && ~@todo && ~@cli\"" || code=$?
    if [[ ${code} = 1 ]]; then
        run_command "bin/behat --strict --no-interaction -vvv -f progress --tags=\"~@javascript && ~@todo && ~@cli\" --rerun" ; code=$?
    fi

    return ${code}
}

run_behat
