#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

run_command "cp etc/travis/suites/application/assets/old-behat.yml behat.yml" || code=$?
run_command "sed -i 's/en_US/fr_FR/' app/config/config_test.yml" || code=$?
