#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

run_command "cp behat-old.yml.dist behat.yml" || code=$?
run_command "sed -i 's/en_US/fr_FR/' config/packages/test/translation.yaml" || code=$?
run_command "bin/console cache:clear --no-warmup --env=test" || code=$?
