# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :jdj do |jdj_config|
        jdj_config.vm.box = "debian/jessie64"

        jdj_config.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 2048
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        end

        jdj_config.vm.synced_folder "./../../", "/var/www/jdj", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'nolock', 'actimeo=2']
        jdj_config.vm.network "private_network", ip: "10.0.0.200"

        # Shell provisioning
        jdj_config.vm.provision :shell, :path => "shell_provisioner/run.sh"
        jdj_config.vm.provision :shell, privileged: false, path: "shell_provisioner/module/app.sh"
    end
end