<?php

/*
 * This file is part of the Jedisjeux project.
 *
 * (c) Jedisjeux
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Document;

use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;
use Sylius\Component\Resource\Model\ResourceInterface;
use Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock as BaseImagineBlock;

/**
 * @author Loïc Frémont <loic@mobizel.com>
 *
 * @PHPCR\Document(referenceable=true)
 */
class ImagineBlock extends BaseImagineBlock implements ResourceInterface
{
    /**
     * SingleImageBlock constructor.
     */
    public function __construct()
    {
        $this->name = uniqid('block_');
    }

    /**
     * {@inheritdoc}
     */
    public function setImage($image = null)
    {
        // prevent overwrite existing image
        if (null === $image) {
            $image = $this->image;
        }

        return parent::setImage($image); // TODO: Change the autogenerated stub
    }
}
